#!/bin/bash

# ==============================================================================
# CONSTANTS
# ==============================================================================
SEED=722

NODES=40
TASKS=40
USERS=20

COMMUNITIES=true

N_REPLICAS=$NODES
MUTATION_PROB_MOVE=0.2
MUTATION_PROB_MOVE_LIST=(0.1 0.2 0.3)
MUTATION_PROB_CHANGE=0.1
MUTATION_PROB_CHANGE_LIST=(0.1 0.2 0.3)

POP_SIZE=500
N_GEN=200
ALGORITHM='NSGA2'
ALGORITHMS=('NSGA2')

SAMPLING_VERSION=0
SAMPLING_VERSION_LIST=(0)
CROSSOVER_VERSION=2
CROSSOVER_VERSION_LIST=(2)
MUTATION_VERSION=1
MUTATION_VERSION_LIST=(0 1 2)

N_PARTITIONS=32
LAMBDA_LIST='0.1 0.3 0.5 0.7 0.9'

OBJECTIVES=('distance' 'nodes')
N_OBJECTIVES=2

N_EXECUTIONS=4
SEED2=1

NTW_PREFIX="data/networks"
SOL_PREFIX="data/solutions"

PREFIX="data/solutions/P$POP_SIZE-G$N_GEN/MM$MUTATION_PROB_MOVE-MC$MUTATION_PROB_CHANGE/new_crossover"
PREFIX2="data/solutions/P$POP_SIZE-G$N_GEN/MM$MUTATION_PROB_MOVE-MC$MUTATION_PROB_CHANGE/communities"


